let products=[    
    {id:1,title:"Micromotor with contra (china)",price:6750,price2:6500,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/micromotor.jpg',description:"",cat:3},
    {id:2,title:"Wax knife",price:45,price2:32,source:"https://raw.githubusercontent.com/Valcon-Developers/images-product/main/wax%20knife.jpeg",description:"",cat:3},
    {id:3,title:"Wax Carver",price:45,price2:32,source:"https://raw.githubusercontent.com/Valcon-Developers/images-product/main/wax%20carver.jpeg",description:"",cat:3},
    {id:4,title:"Basbosa knife ",price:20,price2:16,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/basbosakinife.webp',description:"",cat:3},
    {id:5,title:"Pink wax (cavex)",price:170,price2:162,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/pink%20wax.jpeg',description:"",cat:3},
    {id:6,title:"Glass slabs x2",price:20,price2:8,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/glass%20slap.jpeg',description:"",cat:3},
    {id:7,title:"Articulator",price:400,price2:360,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/artiulator.jpeg',description:"",cat:3},
    {id:8,title:"Torch",price:150,price2:140,source:"https://raw.githubusercontent.com/Valcon-Developers/images-product/main/torch.jpeg",description:"",cat:3},
    {id:9,title:"Acrylic bur",price:100,price2:90,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/acrylic%20bur.jpeg',description:"",cat:3},  
    {id:10,title:"Rubber bow x2",price:30,price2:24,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/rubber%20bow.jpg',description:"",cat:3},
    {id:11,title:"Acrostone",price:305,price2:305,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/acrostone.jpeg',description:"",cat:3},
    {id:12,title:"Dental stone",price:20,price2:15,source:"https://raw.githubusercontent.com/Valcon-Developers/images-product/main/dental%20stone.jpeg",description:"",cat:3},
    {id:13,title:"Mixing spatula Metal",price:20,price2:17,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/spatula%20metal.jpg',description:"",cat:3},
    {id:14,title:"Surgical handle",price:35,price2:32,source:"https://raw.githubusercontent.com/Valcon-Developers/images-product/main/surgical%20handel.jpeg",description:"",cat:3},   
    {id:15,title:"Surgical blade size 15 X3",price:10,price2:6,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/surgical%20blade.jpg',description:"",cat:3},
    {id:16,title:"Separating medium",price:8,price2:5,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/separating%20medium.jpg',description:"",cat:3},
    {id:17,title:"Napkin",price:40,price2:37.5,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/napkin.jpeg',description:"",cat:3},
    {id:18,title:"edentulous stone casts",price:20,price2:7,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/edentulas%20stone%20casts.jpeg',description:"upper and lower edentulous stone casts",cat:3},
    {id:19,title:"Mask",price:40,price2:30,source:"https://raw.githubusercontent.com/Valcon-Developers/images-product/main/mask.jpeg",description:"",cat:3},
    {id:20,title:"Dental film barrier",price:150,price2:110,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/dental%20film%20barier.jpg',description:"",cat:3},
    {id:21,title:"Toolbox size 17",price:390,price2:360,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/box.jpg',description:"",cat:3},
    {id:22,title:"Mirror + Hand",price:45,price2:32,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/mirror.jpg',description:"",cat:3},
    {id:23,title:"Probe",price:45,price2:32,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/probe.jpeg',description:"",cat:3},
    {id:24,title:"Tweezer",price:45,price2:40,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/tweezer.jpeg',description:"",cat:3},
    {id:25,title:"Periodontal probe",price:45,price2:32,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/periodontal%20probe.jpeg',description:"",cat:3},
    {id:26,title:"Air Motor Dentist",price:850,price2:625,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/air%20motor.jpeg',description:"",cat:3},
    {id:27,title:"Straight Handpiece",price:750,price2:720,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/straight%20handpiece.webp',description:"",cat:3},
    {id:28,title:"Magnet cast",price:230,price2:210,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/magnetic%20cast.jpg',description:"Magnet cast + Acrylic anterior and posterior teeth not Elbanna Cast",cat:3},
    {id:29,title:"Low diamond stones X 5",price:100,price2:80,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/low%20stones.jpg',description:" (,cat:3},
    {id:30,title:"Burs Low Speed X 4",price:160,price2:128,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/low%20burs.jpg',description:"",cat:3},
    {id:31,title:"Tofflemire Matrix Holder",price:95,price2:93,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/tofflemire%20matrix.jpeg',description:"",cat:3},
    {id:32,title:"Tofflemire Matrix Bands",price:10,price2:7,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/toddlemire%20matrix%20band.jpg',description:"",cat:3},
    {id:33,title:"Polishing Discs",price:175,price2:165,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/polishing%20discs.webp',description:"Finishing & Polishing Discs",cat:4},
    {id:34,title:"1 kit of composite",price:175,price2:165,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/1%20kit%20composite.jpeg',description:"1 kit of assorted shapes/sizes",cat:4},
    {id:35,title:"Composite applicator",price:45,price2:32,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/compsoite%20aplicator.jpg',description:"",cat:4},
    {id:36,title:"Amalgam Capsules x 8",price:280,price2:248,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/amakgam%20cpsule.jpg',description:"",cat:4},
    {id:37,title:"Amalgam Morter",price:25,price2:20,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/morter.jpeg',description:"Amalgam Morter & Pestle",cat:4},
    {id:38,title:"Amalgam Carrier",price:95,price2:91,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/amalgam%20carrier.jpg',description:"",cat:4},
    {id:39,title:"Amalgam Condenser X2",price:90,price2:64,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/amalgam%20condenser.jpeg',description:"Amalgam Condenser (1 Small Condenser 1 Large Condenser)",cat:4},
    {id:40,title:"Amalgam Carver",price:45,price2:32,source:'https://github.com/Valcon-Developers/images-product/blob/main/amalgam%20carver_.jpg?raw=true',description:"",cat:4},
    {id:41,title:"Anatomical Burnisher",price:45,price2:32,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/anatomical%20burnishure.jpg',description:"",cat:4},
    {id:42,title:"Ball Burnisher",price:45,price2:32,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/ball%20burnisher.jpg',description:"",cat:4},
    {id:43,title:"Wooden Wedges",price:135,price2:125,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/wooden%20wedges.jpeg',description:"",cat:4},
    {id:44,title:"Backaple Composite ruby X1",price:170,price2:140,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/backaple%20composite.jpg',description:"",cat:4},
    {id:45,title:"Flowable Composite X 1",price:170,price2:160,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/flowable.jpg',description:"",cat:4},
    {id:46,title:"Universal Adhesive",price:260,price2:200,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/dhesive%20universal.jpg',description:"",cat:4},
    {id:47,title:"Micro-Brushes for Adhesive",price:45,price2:38,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/maicro%20brush.jpeg',description:"",cat:4},
    {id:48,title:"Sectional Matrix System",price:240,price2:160,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/sectional%20matrix.jpg',description:"Sectional Matrix System (Ring and Bands)",cat:4},
    {id:49,title:"Celluloid Strips",price:70,price2:62,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/celluloid%20strips.jpg',description:"",cat:4},
    {id:50,title:"Finishing strips",price:10,price2:7,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/finishing%20stirips.jpeg',description:"",cat:4},
    {id:51,title:"Light curing unit RTA",price:1350,price2:1210,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/light%20cure.jpg',description:"RTA Pro",cat:4},
    {id:52,title:"putty silicona condensacion BMS",price:750,price2:650,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/index%20putty.webp',description:"",cat:3},
    {id:53,title:"High speed contra (dental)",price:1500,price2:1150,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/hight%20speed.jpeg',description:"",cat:4},
    {id:54,title:"Gloves",price:150,price2:135,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/gloves.jpeg',description:"",cat:3},
    {id:55,title:"Oil Spray",price:140,price2:130,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/oil%20spray.jpeg',description:"",cat:3},
    {id:56,title:"Acrylic teeth size 16",price:70,price2:62,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/acrylic%20teetyh%20size%2016.jpeg',description:"Acrylic resin teeth size 16 (Anterior and posterior)",cat:3},
    //{id:57,title:"low speed contra strong",price:3300,price2:2900,source:'https://github.com/Valcon-Developers/images-product/blob/main/conta%20low%20speed.jpg?raw=true',description:"",cat:3},
    {id:58,title:"Polishing Brushes X 10",price:30,price2:25,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/polishing%20brush.jpeg',description:"",cat:4},
    {id:59,title:"Round Bur High",price:40,price2:32,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/burs%20hight.jpg',description:"",cat:4},
    {id:60,title:"Hight diamond stone x 2",price:20,price2:10,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/stons%20hight.jpeg',description:"",cat:4},
    {id:61,title:"charm temprycrown",price:1550,price2:1500,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/temposray%20crown.jpg',description:"",cat:5},
    {id:62,title:"Isolation Kit",price:1240,price2:1200,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/isolation%20kit.jpeg',description:"",cat:3},
    {id:63,title:"Spreader",price:85,price2:75,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/spreader.jpg',description:"",cat:5},
    {id:64,title:"gutta percha 45-80",price:100,price2:75,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/gutta%20bercha%2045-80.jpg',description:" 15 - 40",cat:5},    
    {id:65,title:"gutta percha 15-40",price:100,price2:75,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/gutta%20bercha%2015-40.webp',description:" 45 - 80",cat:5},    
    {id:66,title:"Aliginate",price:350,price2:150,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/alginate.jpg',description:"Normal set",cat:5},    
    {id:67,title:"Sectional Tray",price:10,price2:8.5,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/sectional%20tray.jpg',description:"",cat:5},
    {id:68,title:"Full-arch tray",price:30,price2:25.5,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/full%20arch%20tray.jpeg',description:"",cat:5},    
    {id:69,title:"Alginate Spatula",price:20,price2:15,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/alginate%20spatula.jpeg',description:"",cat:5},
    {id:70,title:"Green stick compound X3",price:120,price2:90,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/green%20nstick%20compund.jpeg',description:"",cat:6},
    {id:71,title:"K Files 10",price:60,price2:48,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/k%20file%2010.jpeg',description:"",cat:4},
    {id:72,title:"K Files  15-40",price:60,price2:48,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/k%20file%2015-40.jpg',description:"",cat:4},
    {id:73,title:"K Files  45-80",price:60,price2:48,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/k%20file%2045-80.jpeg',description:"",cat:4},
    {id:74,title:"H Files  45-80",price:60,price2:48,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/h%20file%2045-80.jpg',description:"",cat:4},    
    {id:75,title:"PHOSPHORIC ACID ETCH",price:40,price2:25,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/phosphoric%20acid%20etch.jpg',description:"PHOSPHORIC ACID ETCH WITH DISPOSABLE TIPS ",cat:4},
    {id:76,title:"Files Holder"        ,price:25,price2:20,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/file%20holder.jpeg',description:"FILE HOLDER OR BANKER’S SPONGE",cat:4},
    {id:77,title:"ENDODONTIC RULER"    ,price:15,price2:10,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/endodontic%20ruler.jpg',description:"",cat:4},
    {id:80,title:"Sealers",price:650,price2:545,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/sealer.jpeg',description:"",cat:5},
    {id:81,title:"gun",price:420,price2:310,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/gun.jpg',description:"",cat:5},
    {id:82,title:"Post & core ",price:140,price2:100,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/post%20and%20core.png',description:"",cat:6},
    {id:83,title:"celluloid  crown anterior x 4 ",price:80,price2:0,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/celluloid%20crown.webp',description:"",cat:6},
    {id:84,title:"Dental Gates",price:185,price2:175,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/dental%20gates.jpg',description:"",cat:6},
    {id:85,title:"Remove Design Wax",price:270,price2:220,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/design%20wax.jpg',description:"",cat:4},
    {id:86,title:"Sensor apixia",price:3500,price2:0,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/sensor.jpg',description:"",cat:5},
    {id:87,title:"Charm Flex",price:430,price2:0,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/charm.jpg',description:"",cat:6},
    {id:88,title:"Apix Locator",price:8250,price2:8000,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/locator.jpeg',description:"",cat:6},
    {id:89,title:"Sedation Needel x 4",price:20,price2:0,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/needel.avif',description:"",cat:6},
    {id:90,title:"Sedation carboles X 2",price:50,price2:33,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/carboles.jpg',description:"",cat:6},
    {id:91,title:"Excavator",price:45,price2:32,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/excavator.jpg',description:"",cat:5},
    {id:92,title:"Sedation Syrange korean",price:245,price2:240,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/syrange.jpg',description:"",cat:6},
    {id:93,title:"Endo Motor (dentist)",price:4750,price2:4500,source:'https://raw.githubusercontent.com/Valcon-Developers/images-product/main/endomotor.jpg',description:"",cat:6},
   
]
